-- ============================================================
-- SUPABASE MIGRATION: Sistem Perizinan Santri
-- Pesantren Tanwirul Qulub
-- Migrasi dari MySQL → PostgreSQL (Supabase)
-- Tanggal: 3 April 2026
-- ============================================================
-- JALANKAN SELURUH FILE INI DI SUPABASE SQL EDITOR
-- ============================================================

-- ============================================================
-- FASE 1: DATABASE SCHEMA
-- ============================================================

-- =========================
-- TABEL: santri
-- =========================
CREATE TABLE IF NOT EXISTS public.santri (
  id_santri BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nis VARCHAR(20) UNIQUE NOT NULL,
  nama_santri VARCHAR(100) NOT NULL,
  jenis_kelamin VARCHAR(1) NOT NULL CHECK (jenis_kelamin IN ('L', 'P')),
  kelas VARCHAR(20) NOT NULL,
  status VARCHAR(10) DEFAULT 'aktif' CHECK (status IN ('aktif', 'nonaktif')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- TABEL: admin_profiles
-- Linked ke Supabase Auth (auth.users)
-- =========================
CREATE TABLE IF NOT EXISTS public.admin_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username VARCHAR(50) UNIQUE NOT NULL,
  nama_admin VARCHAR(100),
  role VARCHAR(20) DEFAULT 'admin' CHECK (role = 'admin'),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- TABEL: santri_profiles
-- Linked ke Supabase Auth (auth.users)
-- =========================
CREATE TABLE IF NOT EXISTS public.santri_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  id_santri BIGINT REFERENCES public.santri(id_santri) ON DELETE CASCADE,
  username VARCHAR(50) UNIQUE NOT NULL,
  role VARCHAR(20) DEFAULT 'santri' CHECK (role = 'santri'),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- TABEL: izin
-- =========================
CREATE TABLE IF NOT EXISTS public.izin (
  id_izin BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_santri BIGINT NOT NULL REFERENCES public.santri(id_santri) ON DELETE CASCADE,
  jenis_izin VARCHAR(20) NOT NULL CHECK (jenis_izin IN ('sakit', 'acara_keluarga', 'pulang', 'keluar', 'lainnya')),
  tanggal_keluar TIMESTAMPTZ NOT NULL,
  batas_waktu TIMESTAMPTZ,
  tanggal_kembali TIMESTAMPTZ,
  alasan TEXT,
  status VARCHAR(15) DEFAULT 'menunggu' CHECK (status IN ('menunggu', 'disetujui', 'ditolak')),
  status_kembali VARCHAR(15) CHECK (status_kembali IN ('tepat_waktu', 'terlambat')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================
-- FUNCTION: auto update updated_at
-- =========================
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_santri_updated
  BEFORE UPDATE ON public.santri
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER on_izin_updated
  BEFORE UPDATE ON public.izin
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- =========================
-- INDEX untuk performa query
-- =========================
CREATE INDEX idx_izin_id_santri ON public.izin(id_santri);
CREATE INDEX idx_izin_status ON public.izin(status);
CREATE INDEX idx_izin_tanggal ON public.izin(tanggal_keluar DESC);
CREATE INDEX idx_santri_nis ON public.santri(nis);
CREATE INDEX idx_santri_profiles_id_santri ON public.santri_profiles(id_santri);


-- ============================================================
-- FASE 2: AUTH TRIGGERS + RLS POLICIES
-- ============================================================

-- =========================
-- TRIGGER: Auto-create profile on signup
-- =========================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.raw_user_meta_data->>'role' = 'admin' THEN
    INSERT INTO public.admin_profiles (id, username, nama_admin, role)
    VALUES (
      NEW.id,
      NEW.email,
      COALESCE(NEW.raw_user_meta_data->>'nama', NEW.email),
      'admin'
    );
  ELSIF NEW.raw_user_meta_data->>'role' = 'santri' THEN
    INSERT INTO public.santri_profiles (id, id_santri, username, role)
    VALUES (
      NEW.id,
      (NEW.raw_user_meta_data->>'id_santri')::BIGINT,
      NEW.email,
      'santri'
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- =========================
-- RLS: santri
-- =========================
ALTER TABLE public.santri ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin can view all santri" ON public.santri
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.admin_profiles WHERE id = (SELECT auth.uid()))
  );

CREATE POLICY "Admin can insert santri" ON public.santri
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.admin_profiles WHERE id = (SELECT auth.uid()))
  );

CREATE POLICY "Admin can update santri" ON public.santri
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.admin_profiles WHERE id = (SELECT auth.uid()))
  );

CREATE POLICY "Admin can delete santri" ON public.santri
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM public.admin_profiles WHERE id = (SELECT auth.uid()))
  );

CREATE POLICY "Santri can view own data" ON public.santri
  FOR SELECT USING (
    id_santri IN (
      SELECT sp.id_santri FROM public.santri_profiles sp WHERE sp.id = (SELECT auth.uid())
    )
  );

CREATE POLICY "Anon can view santri for registration" ON public.santri
  FOR SELECT TO anon USING (true);


-- =========================
-- RLS: izin
-- =========================
ALTER TABLE public.izin ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin can view all izin" ON public.izin
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.admin_profiles WHERE id = (SELECT auth.uid()))
  );

CREATE POLICY "Admin can update izin" ON public.izin
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.admin_profiles WHERE id = (SELECT auth.uid()))
  );

CREATE POLICY "Santri can view own izin" ON public.izin
  FOR SELECT USING (
    id_santri IN (
      SELECT sp.id_santri FROM public.santri_profiles sp WHERE sp.id = (SELECT auth.uid())
    )
  );

CREATE POLICY "Santri can insert own izin" ON public.izin
  FOR INSERT WITH CHECK (
    id_santri IN (
      SELECT sp.id_santri FROM public.santri_profiles sp WHERE sp.id = (SELECT auth.uid())
    )
  );

CREATE POLICY "Santri can update own izin" ON public.izin
  FOR UPDATE USING (
    id_santri IN (
      SELECT sp.id_santri FROM public.santri_profiles sp WHERE sp.id = (SELECT auth.uid())
    )
  );


-- =========================
-- RLS: admin_profiles
-- =========================
ALTER TABLE public.admin_profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin can view own profile" ON public.admin_profiles
  FOR SELECT USING ((SELECT auth.uid()) = id);


-- =========================
-- RLS: santri_profiles
-- =========================
ALTER TABLE public.santri_profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own santri profile" ON public.santri_profiles
  FOR SELECT USING ((SELECT auth.uid()) = id);

CREATE POLICY "Admin can view all santri profiles" ON public.santri_profiles
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.admin_profiles WHERE id = (SELECT auth.uid()))
  );


-- ============================================================
-- SEED DATA
-- ============================================================
INSERT INTO public.santri (nis, nama_santri, jenis_kelamin, kelas) VALUES
  ('12345667', 'Fadlia Nur Azizah', 'P', 'Ula'),
  ('12345668', 'Deden Ramdhan', 'L', 'Ulya'),
  ('12345669', 'Naila Sahru N', 'P', 'Wustho');

-- ============================================================
-- CATATAN PENTING:
-- 1. Setelah menjalankan SQL ini, buka Authentication > Settings
--    - Matikan "Enable email confirmations"  
--    - Matikan "Double confirm email changes"
--    - Set minimum password length: 6
-- 2. Buat akun admin pertama via Authentication > Users > Add User:
--    - Email: admin@pesantren.local
--    - Password: admin123
--    - Metadata: {"role": "admin", "nama": "Admin Utama"}
-- ============================================================
